### ISSUE TITLE
Factories

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-pretenderify#1]
Being built in the add-factory branch.

**Factory** 
- [x] Factory.define
- [x] work with basic numbers, strings
- [x] work with functions that have access to sequence
- [ ] basic inheritance

**create, createList**
- [x] basic functionality
- [x] allow override of attrs

**additional features**
- [ ] traits
- [ ] relationships
- [ ] fake data via Faker.js

**Comment by samselikoff** [comment]
I like this api:

```js
import EP from 'ember-pretenderify';

export default EP.Factory.define({

  name: EP.faker('name'),
  age: 20,

  email: function(self, n) {
    return `person${n}@test.com`;
  },

  admin: function(self) {
    return self.age > 30;
  }
});
```

**Comment by samselikoff** [comment]
`faker` is going to be [this guy](https://github.com/marak/Faker.js/).

**Comment by marcioj** [comment]
Hi Sam, I found pretty interesting the factory idea. One question: Are you planning in add mixins/trait and factory inheritance support?

**Comment by samselikoff** [comment]
I'm basically trying to copy as much of the factory_girl API as possible. Traits are definitely on the roadmap...what are mixins in this context? And inheritance support should absolutely be supported, thanks for mentioning.

**Comment by marcioj** [comment]
Great! By mixins I meant the same concept of traits in factory girl.
I was thinking about some API which could also support traits and factory inheritance, this is what comes to my mind. Just a suggestion :)

```js
import { define, build } from 'ember-pretenderify/factory';
 
function add(a,b) {
  return a+b;
}
 
export default define(function() {
  this.factory('order', function() {
 
    this.customer_name = 'Mr foobar';
    this.delivery_address = 'foobar street';
    this.items = [];
    this.status = 'new';
 
    this.total = function() {
      return this.items.map(function(item) {
        return item.price;
      }).reduce(add, 0);
    };
 
    this.factory('order_with_itens', function() {
      this.items = [build('order_item')];
    });
  });
 
  this.trait('pending_payment', function() {
    this.status = 'pending';
  });
});
 
// usage
order = build('order');
order.delivery_address; // 'foobar street'
order = build('order', delivery_address: 'other address');
order.delivery_address; // 'other address'
order = build('order_with_items');
order.items.length // 1
order = build('order', 'pending_payment');
order.status // 'pending'
```
Basically a conversion of factory girl's DSL to javascript.

**Comment by samselikoff** [comment]
@marcioj gotcha, yep I definitely am planning on doing traits.

You can see the API I started out with here: https://github.com/samselikoff/ember-pretenderify/blob/add-factories/tests/factories/contact.js. It's working in that branch. You can see the use [here](https://github.com/samselikoff/ember-pretenderify/blob/add-factories/tests/acceptance/contacts-test.js#L10). I'm not sure we need the build/create distinction here - I think I'm going to use create for now, since it adds them directly to the store.

I'm also planning on adding Faker.js so you can do things like

```js
name: EP.Faker('name')
```

The `total` example you have above is interesting, wouldn't that be something that already lives on the model? The purpose of these factories is just to get data into the server's "database".

You can look at the tests for [factories](https://github.com/samselikoff/ember-pretenderify/blob/add-factories/tests/unit/factory-test.js) and [create](https://github.com/samselikoff/ember-pretenderify/blob/add-factories/tests/unit/server-test.js#L32) to see what functionality I currently have.

I haven't implemented factory inheritance yet but it's on the roadmap. I'd like it to match the typical Ember CLI inheritance workflow, i.e. `import blah from './blah'`; export blah.extend`, even though factories aren't going to be `Ember.Object`s. `this.factory(name)` requires some global register and I'd prefer not to do that, I just want to load the factories into the server definition (you can see how I'm doing it currently [here](https://github.com/samselikoff/ember-pretenderify/blob/add-factories/app/initializers/ember-pretenderify.js#L29-L30)).

Thoughts?

**Comment by samselikoff** [comment]
Created additional issues for the rest of the items, wanted to go ahead and cut a release with the current functionality

**Comment by marcioj** [comment]
Great work @samselikoff! This is definitely the way I would like to mock data in ember tests.
