### ISSUE TITLE
Exclude data from production build

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-pretenderify#17]
Right now, the server doesn't run in production (unless force is specified), but all the data + route definitions end up in `app.js`. Is it possible to exclude these files?

**Comment by marcioj** [comment]
I believe it's possible overriding the [`treeFor`](https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md#treefor) hook. I will check it out.

**Comment by samselikoff** [comment]
awesome, thanks man!

**Comment by samselikoff** [comment]
@marcioj I just verified this worked with a brand new app. Thanks again for your help!

Another question. I see the files under `app/pretender` still get included. Do you know if it's possible to exclude these from the build tree in production?

**Comment by marcioj** [comment]
Good catch @samselikoff. I believe that #22 should fix it. Can you give a look?

**Comment by samselikoff** [comment]
Verified this works, thanks again
