### ISSUE TITLE
Cannot get record in tests

### ISSUE THREAD

**Issue by cibernox** [samselikoff/ember-pretenderify#33]
I'm not sure of that's going on, but I can't get individial records in tests.

The exact error is: 
```
Pretender intercepted GET /api/schools/1 but encountered an error: Cannot read property 'findBy' of undefined
```
that references to this line: https://github.com/samselikoff/ember-pretenderify/blob/ab7f70d0073e14a047ac753152d39573743212e7/addon/store.js#L27

My config.js:

```js
export default function() {
  this.namespace = 'api';
  this.timing = 100;

  this.get('/schools/:id');
  this.get('/schools');
  this.get('/teachers/:id');
  this.get('/teachers');
}
```

and my fixtures in `app/pretender/data/schools.js`

```js
export default [
  {
    id: 1,
    name: "Copley High School",
    subdomain: "copley",
    school_type: 'secondary_school',
    address: '11 Test Road',
    teachers: [1, 2]
  }, {
    id: 2,
    name: "Tendring Tech",
    subdomain: "tendringtech",
    school_type: 'secondary_school',
    address: '11 Test Road',
    teachers: [3]
  }, 
  /* and a few more */
];
```

Everything seems to be by the book, but in my acceptance tests it fails. The only special bit is that I'm using `ember-cli-simple-auth` and `ember-cli-simple-auth-oauth2`, but I don't see why it would affect this.

I'm open to pairing to fix this is that helps

**Comment by samselikoff** [comment]
Some better error handling would sure be helpful :) 

Does it work in development? i.e. when you run `ember serve`?

The fixtures don't actually work in tests, you use factories instead. [Check out the acceptance testing section](https://github.com/samselikoff/ember-pretenderify#acceptance-testing) part of the readme and let me know if it makes sense.

**Comment by cibernox** [comment]
@samselikoff I saw this after opening this PR. I was fighting this error yesterday afternoon and this morning you release the new version with the factories. #maximum-trolling

**Comment by cibernox** [comment]
I'll close this while I explore the possibility of using factories. Factories look more interesting that just using static fixtures.

**Comment by samselikoff** [comment]
Haha, ok great. The wiki has the guides now, too, fyi.

The fixtures are really there to be an easy way to get some test data in for development
