### ISSUE TITLE
Factories error: myapp/tests/factories/school.jshint must export a factory

### ISSUE THREAD

**Issue by cibernox** [samselikoff/ember-pretenderify#34]
I can't make factories work, I get this weird error. Someone thinks that I am not exporting a factory.

The factory in `tests/factories/school.js`

```js
import EP from 'ember-pretenderify';

export default EP.Factory.extend({
  name: function(i) {
    return "School " + i;
  },

  subdomain: function(i) {
    return this.name.replace(' ', '-');
  },
  school_type: 'expensive',
  address: '2 Some Street, London',
  teacher_ids: []
});
```

The acceptance in `tests/acceptance/schools/show-test.js`

```js
import Ember from 'ember';
import { module, test } from 'qunit';
import startApp from '../../helpers/start-app';

var application;
var school;

module('Acceptance: School Show', {
  beforeEach: function() {
    application = startApp();
    school = server.create('school');
  },
  afterEach: function() {
    Ember.run(application, 'destroy');
  }
});

/* Some tests */
```

**Comment by samselikoff** [comment]
So currently in factories you cannot have attributes that depend on other dynamic attributes. In your case `subdomain` depends on `name` - does it work if you change that?

**Comment by cibernox** [comment]
Let me check

**Comment by cibernox** [comment]
No, it makes no difference. Same error.

**Comment by samselikoff** [comment]
what's the error?

**Comment by cibernox** [comment]
The one in the title of the PR, but I've taken a screenshot:

![error](https://www.evernote.com/shard/s36/sh/6c07b3f4-9f46-43d4-8b2b-15077546c80d/37bd8b238909ee2c41175b3a5d5ed36e/res/4339392f-82c6-4565-abaa-51d327722648/skitch.png)

**Comment by samselikoff** [comment]
is the file called .jshint instead of .js?

**Comment by cibernox** [comment]
No, that is exactly the mindfuck.

**Comment by samselikoff** [comment]
Bizarre, I cannot reproduce right now. What version of CLI?

**Comment by cibernox** [comment]
I've just updated: 0.2.0.beta1

**Comment by samselikoff** [comment]
Hm okay, I'll have to test on that version. I'll have to look at this a bit later - sorry for the error, and thanks for helping out!

**Comment by cibernox** [comment]
My pleasure. Let me know if you can't reproduce it. I might be able to build a sample app or pair.

**Comment by ashton** [comment]
Same problem here, I tried to create an instance on the console, but it didn't found any factory to handle it, and there is a file called **classifications.js** on the specified path (*tests/factories/classfication.js*).

![screenshot from 2015-02-26 12 24 28](https://cloud.githubusercontent.com/assets/95974/6394722/3e892436-bdb2-11e4-86bf-5db0f78e9749.png)

**Comment by samselikoff** [comment]
@ashton ember cli version?

**Comment by samselikoff** [comment]
Ok, I'm able to reproduce with 2.0 beta. Let me look into this.

**Comment by samselikoff** [comment]
Should be all set, just upgrade to 0.19. Apparently .jshint files were being autogenerated in the tree for these files.

**Comment by cibernox** [comment]
updating...

**Comment by cibernox** [comment]
Fixed for me :+1:

**Comment by ashton** [comment]
Wow! Thank you for the quick fix!

**Comment by samselikoff** [comment]
sure thing! This project is really new, I'm happy to help out anyone that wants to give it a try
